urgences/urls.py
# coding: utf-8
from django.conf.urls import url
from django.conf.urls import url, include
from django.views.generic import ListView
from django.views.generic import TemplateView
from gestion_patient import views
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static




page =[]
liste_des_elements_de_page = []



urlpatterns = [
	
    
   
    url(r'^admin/', admin.site.urls),
    url(r'^rentrer_patient', views.rentrer_patient, name = 'rentrer_patient'),
    url(r'^afficher_patient', views.afficher_patient, name = 'afficher_patient'),
     url(r'^supprimer_patient', views.supprimer_patient, name = 'afficher_patient'),
     url(r'^realisation_patient', views.realisation_patient, name = 'afficher_patient'),

#____________________________________________CR type________________________________

     url(r'^scanner', views.scanner, name = 'scanner'),

     #RADIO
     url(r'radiographies/$', views.radiographies, name = 'radiographies'),
     url(r'radiographies/pulmonaire/$', views.radiographie_poumon, name = 'radiographies_pulmonaire'),
     url(r'radiographies/cheville/$', views.radiographie_cheville, name = 'radiographies_cheville'),
     url(r'radiographies/epaule/$', views.radiographie_epaule, name = 'radiographies_epaule'),
     url(r'radiographies/genou/$', views.radiographie_genou, name = 'radiographies_genou'),
     url(r'radiographies/poignet/$', views.radiographie_poignet, name = 'radiographies_poignet'),
     url(r'radiographies/coude/$', views.radiographie_coude, name = 'radiographies_coude'),
     url(r'radiographies/pied/$', views.radiographie_pied, name = 'radiographies_pied'),
     url(r'radiographies/main/$', views.radiographie_main, name = 'radiographies_main'),
     url(r'radiographies/bassin/$', views.radiographie_bassin, name = 'radiographies_bassin'),
     url(r'radiographies/rachis lombaire/$', views.radiographie_rachis_lombaire, name = 'radiographies_rachis_lombaire'),
     url(r'radiographies/rachis dorsal/$', views.radiographie_rachis_dorsal, name = 'radiographies_rachis_dorsal'),
     url(r'radiographies/rachis cervical/$', views.radiographie_rachis_cervical, name = 'radiographies_rachis_cervical'),
     url(r'radiographies/bras/$', views.radiographie_bras, name = 'radiographies_bras'),
     url(r'radiographies/jambe/$', views.radiographie_jambe, name = 'radiographies_jambe'),
     url(r'radiographies/avant_bras/$', views.radiographie_avant_bras, name = 'radiographies_avant_bras'),
     url(r'radiographies/cuisse/$', views.radiographie_cuisse, name = 'radiographies_cuisse'),

     #IRM
     url(r'irm/$', views.irm, name = 'irm'),
     url(r'irm/cardiaque/$', views.irm_cardiaque, name = 'irm_cardiaque'),
     url(r'irm/prostate/$', views.irm_prostate, name = 'irm_prostate'),
     url(r'irm/cerebrale/$', views.irm_cerebrale, name = 'irm_cerebrale'),
     url(r'irm/foie/$', views.irm_foie, name = 'irm_foie'),
     url(r'irm/genou/$', views.irm_genou, name = 'irm_genou'),
     url(r'irm/rachis_lombaire/$', views.irm_rachis_lombaire, name = 'irm_rachis_lombaire'),


     url(r'commandeVocale/$', views.commandeVocale, name = 'commandeVocale'),

     url(r'^accueil', views.accueil, name = 'accueil'),
    ]

gestion_patient/models.py
#coding: utf-8
from django.db import models

# Create your models here.


class Demande(models.Model):
   
    degre_urgence_choix = (
        ('H24', 'H24'),
        ('immédiat', 'immédiat'),
    )
    
    type_examen_choix = (
        ('scanner cerebral', 'scanner cerebral'),
        ('scanner AP', 'scanner AP'),
        ('scanner TAP', 'scanner TAP'),
        ('angioscanner pulmonaire', 'angioscanner pulmonaire'),
        ('uroscanner', 'uroscanner'),
        ('scanner Thoracique', 'scanner thoracique'),
    )
    injection_choix = (
        ('oui', 'oui'),
        ('non', 'non'),
        ('à voir', 'à voir')
    )
    realisation_choix =(
        ('oui', 'oui'),
        ('non', 'non'),
    )
    
    
    prenom = models.CharField(max_length=30)
    nom = models.CharField(max_length=30)
    indication = models.CharField(max_length=300, null=True)
    degre_urgence = models.CharField(
        max_length=10,
        choices=degre_urgence_choix)
    type_examen= models.CharField(
        max_length=30,
        choices=type_examen_choix)
    injection = models.CharField(
        max_length=30,
        choices=injection_choix)
    realisation = models.CharField(
        max_length=30, 
        choices=realisation_choix, null=True, default="non")
    suppression = models.CharField(
        max_length=10,
        choices=realisation_choix,null=True, default="non")
    heure= models.DateTimeField(null = True)
    

gestion_patient/forms.py
from django import forms
from django.forms import ModelForm
from gestion_patient.models import Demande


class DemandeForm(ModelForm):
    class Meta:
        model = Demande
        fields = ['nom','prenom', 'indication','degre_urgence','type_examen','injection']
        widgets = {
       'degre_urgence':forms.Select,
       'type_examen':forms.Select,
       'injection':forms.Select, 
       'indication': forms.Textarea,    
        }
        

gestion_patient/views.py
# coding: utf-8

from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, Http404
from django.template import loader
#from django.core.exceptions import ObjectDoesNotExist


from .models import *
from django.contrib.auth.models import* 
from django.contrib.auth import *
from bs4 import BeautifulSoup
from django.template.response import *
import bs4
import re
import pickle
import os
import json
from nltk import *
from bs4 import BeautifulSoup
from random import *
from unidecode import unidecode
from django.utils.safestring import mark_safe
from.forms import DemandeForm
from django.utils import timezone



app_name = 'gestion_patient'

#_____________________classes_______________________#


class Titre:
    def __init__(self, intitule, optionnel, cl):
        self.optionnel = optionnel
        self.intitule = intitule
        self.cl= cl

class Item:

    liste_des_items= []
    liste_des_titres=[]
    liste_des_intitules_des_titres = []

    def __init__ (self, titre_item, label_element, categorie, formule, defaut, optionnel, cible="", dialog="", mini="", maxi="",tooltip="", calcul=""):
        self.titre_item= titre_item
        self.label_element = label_element
        self.formule= formule
        self.categorie = categorie
        if tooltip != "":
            self.categorie = self.categorie + tooltip
        self.tooltip = tooltip
        if self.tooltip == "":
            self.tooltip = "vide"
        self.defaut= defaut
        self.optionnel= optionnel
        self.cible = cible
        self.dialog = dialog
        self.min = mini
        self.max = maxi
        if self.min != "":
            self.moy = (self.min + self.max)/2



        for at in self.__dict__.values():
            at = mark_safe(at)

        Item.liste_des_items.append(self)


        #créer un titre de rubrique optionnel
        if self.titre_item not in Item.liste_des_intitules_des_titres:
            t = Titre(intitule=self.titre_item, optionnel=self.optionnel, cl=self.categorie)
            Item.liste_des_intitules_des_titres.append(t.intitule)
            Item.liste_des_titres.append(t)

class CRTYPE:
    def __init__(self, indication, technique, resultat, conclusion):
        self.indication = indication
        self.technique = technique
        self.resultat = resultat
        self.conclusion = conclusion

    def compte_rendu(self):
        CRTYPE = "INDICATION:"+ "xxxx"+ self.indication + "xxxx" + "TECHNIQUE:" + "xx" + self.technique + "xxxx" + "RESULTAT" + "xx" + self.resultat 
        if self.conclusion != "":
            CRTYPE = CRTYPE +  "xxxx" + "CONCLUSION: " + "xx" + self.conclusion
        CRTYPE = mark_safe(CRTYPE)
        return(CRTYPE)

class Select:
    def __init__(self, titre, listeOption, tooltip="", defaut=""):
        self.titre=titre
        self.listeOption=listeOption
        self.tooltip=tooltip
        self.defaut=defaut

class Carte:
    def __init__(self, titre, listeCase=[], listeSelect=[], calcul="vide", listeLesion = [], listeRange=[]):
        self.titre=titre
        self.listeCase = listeCase
        self.listeSelect = listeSelect
        self.listeRange = listeRange
        self.calcul = calcul
        self.listeLesion = listeLesion

class Etape:
    def __init__(self, question, oui=[], non=[], passer=[], ouiCible = [], nonCible = [], cible="", widget="aucun", titre="", premiere=""):
        self.question= question
        self.oui = oui
        self.non = non
        self.ouiCible = ouiCible
        self.nonCible = nonCible
        self.passer = passer
        self.widget = widget
        self.titre= titre
        self.premiere = premiere
        

class Guide:
    def __init__(self, etapes):
        self.etapes= etapes
        
        
def commandeVocale(request):
    return render(request, 'html/commandeVocale.html')

def remise_a_zero_des_items():
    Item.liste_des_items= []
    Item.liste_des_titres=[]
    Item.liste_des_intitules_des_titres = []


#______________________________CARTES_____________________________________


def carteNodulePulmonaire():
   
    item1 = Item(titre_item="noduleLateralite", label_element="gauche", categorie="resultat", formule="gauche", defaut= "", optionnel="non", cible="")  
    item2 = Item(titre_item="noduleLateralite", label_element="droite", categorie="resultat", formule="droit", defaut= "", optionnel="non", cible="")
    select1 = Select(titre=laterlite, listeOption= [item1,item2])


    item1 = Item(titre_item="noduleContours", label_element="spiculé", categorie="resultat", formule="aux contours spiculés", defaut= "", 
    optionnel="non", cible="") 
    item2 = Item(titre_item="noduleContours", label_element="flous", categorie="resultat", formule="aux contours flous", defaut= "", 
    optionnel="non", cible="")
    item3 = Item(titre_item="noduleContours", label_element="réguliers", categorie="resultat", formule="aux contours réguliers", defaut= "", 
    optionnel="non", cible="")
    Select2 = Select(titre=contours, listeOption=[item1, item2,item3])


    item1 = Item(titre_item="noduleSituation", label_element="lobe supérieur", categorie="resultat", formule="localisé au lobe supérieur", defaut="", optionnel="non", cible="") 
    item2 = Item(titre_item="noduleSituation", label_element="lobe moyen", categorie="resultat", formule="localisé au lobe moyen", defaut="", optionnel="non", cible="")
    item3 = Item(titre_item="noduleSituation", label_element="lobe inférieur", categorie="resultat", formule="localisé au lobe inférieur", defaut="", optionnel="non", cible="")
    Select3 = Select(titre=contours, listeOption=[item1, item2,item3])


    carte1 = Carte(titre = "nodule pulmonaire", listeCase= "", listeSelect = [select1, Select2, select3])

    return carte1

def carteFracture():
    
    #orientation
    item1 = Item(titre_item="fracture orientation", label_element="transverse oblique", categorie="", formule="orientation : transverse oblique", defaut= "", optionnel="non", cible="")   
    item2 = Item(titre_item="fracture orientation", label_element="sagittale oblique", categorie="", formule="orientation : sagittal oblique", defaut= "", optionnel="non", cible="")
    item3 = Item(titre_item="fracture orientation", label_element="coronale oblique", categorie="", formule="orientation : coronal oblique", defaut= "", optionnel="non", cible="")
    item3 = Item(titre_item="fracture orientation", label_element="complexe", categorie="", formule="orientation : complexe", defaut= "", optionnel="non", cible="")
    
    select1 = Select(titre="orientation", listeOption=[item1,item2,item3])

    #déplacement
    item1 = Item(titre_item="non déplacée", label_element="non déplacée", categorie="", formule="déplacement : non", defaut= "", optionnel="non", cible="")   
    item2 = Item(titre_item="peu déplacée", label_element="peu déplacée", categorie="", formule="déplacement : peu déplacé", defaut= "", optionnel="non", cible="")   
    item3 = Item(titre_item=" déplacée", label_element="déplacée", categorie="", formule="déplacement : X mm", defaut= "", optionnel="non", cible="")   
    select2 = Select(titre="déplacement", listeOption=[item1,item2,item3])

    #articulaire
    item1 = Item(titre_item="articulaire", label_element="articulaire", categorie="", formule="articulaire", defaut= "non articulaire", optionnel="non", cible="")   

    listeCase =[item1]

    carte1 = Carte(titre = "fracture", listeCase= listeCase, listeSelect = [select1, select2])
    return carte1    

def carteAnomalieCinetiqueCardiaque():
    
    #orientation
    item1 = Item(titre_item="modérée", label_element=" hypokinésie modérée", categorie="", formule="hypokinésie modérée", defaut= "", optionnel="non", cible="")   
    item2 = Item(titre_item="sévère", label_element="hypokinésie sévère", categorie="", formule="hypokinésie sévère", defaut= "", optionnel="non", cible="")
    item3 = Item(titre_item="akinésie", label_element="akinésie", categorie="", formule="akinésie", defaut= "", optionnel="non", cible="")
    
    select1 = Select(titre="cinétique", listeOption=[item1,item2,item3])

    #déplacement
    item1 = Item(titre_item="paroi antérieure", label_element="paroi antérieure", categorie="", formule="intéressant la paroi antérieure", defaut= "", optionnel="non", cible="")   
    item2 = Item(titre_item="paroi inférieure", label_element="paroi inférieure", categorie="", formule="intéressant la paroi inférieure", defaut= "", optionnel="non", cible="")   
    item3 = Item(titre_item="paroi latérale", label_element="paroi latérale", categorie="", formule="intéressant la paroi latérale", defaut= "", optionnel="non", cible="")   
    select2 = Select(titre="localisation", listeOption=[item1,item2,item3])

    #articulaire
    #item1 = Item(titre_item="articulaire", label_element="articulaire", categorie="", formule="articulaire", defaut= "non articulaire", optionnel="non", cible="")   

    listeCase =[item1]

    carte1 = Carte(titre = "anomalieCinetiqueCardiaque", listeCase= listeCase, listeSelect = [select1, select2])
    return carte1    

def carteIndicationProstate():
    
    #___________________ saisie de nombre: range_____________
        item1 = Item(titre_item="PSA", label_element=" Taux de PSA (ng/mL)", categorie="", formule="Taux de PSA (ng/mL): ", defaut= "", optionnel="non", cible="", mini=0, maxi=100)   
        item2 = Item(titre_item="PSA", label_element=" Rapport PSA (%)", categorie="", formule="Rapport de PSA(%): ", defaut= "", optionnel="non", cible="", mini=0, maxi=100,)   

        listeRange= [item1, item2]

    #_________________SELECT__________________

        #Select1
        item1 = Item(titre_item="Risque élevé", label_element="Risque élevé", categorie="", formule="Risque selon la classification D'Amico: élevé", defaut= "", optionnel="non", cible="", )   

gestion_patient/templates/accueil.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Titre</title>

         <link type="text/css" rel="stylesheet" href="static/materialize/css/materialize.css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
       

        <script type="text/javascript" src="static/materialize/js/materialize.min.js"></script>
    	<script src="static/jquery-3.2.1.js"> </script>
    	
    </head>

    <body class="grey lighten-2">

            

        <div class="titre blue"> <h3>ACCEUIL</h3> </div>
        <div class="section"></div>
        
        <div class="row">
            {% for rubrique in datas.rubriques %}
          <div class="col s7">
                <div class="card white ">
                    <div class="card-content black-text">
                        <a href= "{{rubrique}}" class="waves-effect blue waves-light btn">{{rubrique|capfirst}} </a>
                    </div>
                 </div>
            </div>
            {% endfor %}


      </div>
        
        
       
        
<script>
$(document).ready(function() {
    $('select').material_select();
    $('#id_indication').css("height","100px");
    $('#bouton_afficher').click(function(){
            document.location.href="afficher_patient.html"; 
                });
  });
</script>


 
    </body>
</html>

gestion_patient/templates/afficher_patient.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Titre</title>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="static/materialize/css/materialize.css"/>
         <link type="text/css" rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>

    	<script src="static/jquery-3.2.1.js"> </script>
    	<script type="text/javascript" src="static/materialize/js/materialize.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    </head>

    <body class="grey lighten-2">
    	<div class="row">
          <div class="col s12">
            <div class="card white ">
            <div class="card-content black-text">
                <span> <h2 class= "blue">Liste des patients </h2></span>
                <table class="striped" id="tableau_patients">
        <thead>
          <tr>
              <th>degre d'urgence</th>
              <th>Nom</th>
              <th>prenom</th>
              <th>type d'examen</th>
              <th>indication</th>
              <th>injection</th>
              <th>heure</th>
              <th>fait? </th>
              <th>supprimer la demande</th>
              
          </tr>
        </thead>

        <tbody>
           {% for demande in demandes %}
            {% if demande.supprimer != "oui" %} 
            
          <tr  {% if demande.realisation == "oui" %} style="color:grey" {% endif %} >
              
              {% if demande.degre_urgence == "immédiat" %}
             <td> <a id="urgence" class="btn-floating  waves-effect waves-light orange lighten-1"><i onclick="document.location.href='realisation_patient.html?id={{demande.id}}'" class="material-icons">directions_run</i></a></td>
               {% else %}
               <td> <a id="urgence" class="btn-floating  waves-effect waves-light blue lighten-1"><i onclick="document.location.href='realisation_patient.html?id={{demande.id}}'" class="material-icons">directions_walk</i></a></td>
              {% endif %} 
            <td>{{demande.nom|upper}}</td>
            <td>{{demande.prenom}}</td>
             
             <td>{{demande.type_examen}}</td>
              <td>{{demande.indication}}</td>
              
               {% if demande.injection == "oui" %}
             <td> <a id="urgence" class="btn-floating  waves-effect waves-light grey lighten-1"><i onclick="document.location.href='realisation_patient.html?id={{demande.id}}'" class="material-icons">colorize</i></a></td>
               {% else %}
               <td> </td>
              {% endif %} 
              
          
               
             
              <td><span class="btn grey">{{demande.heure|time:"H:i"}}</span></td>
              
              
              
               <td>
                  {% if demande.realisation != "non" %}
                   <a id="fait" class="btn-floating  waves-effect waves-light green lighten-1"><i onclick="document.location.href='realisation_patient.html?id={{demande.id}}'" class="material-icons">done</i></a>
                  {% else %}
                  <a id="fait_{{demande.id}}" class="btn-floating  waves-effect waves-light red lighten-1"><i onclick="document.location.href='realisation_patient.html?id={{demande.id}}'" class="material-icons">done</i></a></td>
                   {% endif %}
              
              
              <td><a id="supprimer" class="btn  waves-effect waves-light grey lighten-1" onclick="document.location.href='supprimer_patient.html?id={{demande.id}}'"><i class="material-icons">delete</i></a></td>
              
            </tr> 
            {% endif %}
          {% endfor %} 
        </tbody>
      </table>
            </div>
          </div>
        </div>
      </div>
            

       
        
         <button class="btn waves-effect waves-light white" id="rentrer"> <a href="rentrer_patient.html"> rentrer un nouveau patient</a>
        
        <script>
            jQuery('#tableau_patients').dataTable()
           
                  
        </script>
        
        
    </body>
</html>

gestion_patient/templates/radiographies_avant_bras.html
{% extends "radiographies_type.html" %}
{% load static %}

gestion_patient/templates/radiographies_bassin.html
{% extends "radiographies_type.html" %}
{% load static %}

gestion_patient/templates/radiographies_coude.html
{% extends "radiographies_pulmonaire.html" %}
{% load static %}


{% block autre_script %}


	<script>


	function copyToClipboard(element, id) {
									        textRange = $(id);
									        
									        textRange.html(element)
									        //$(textRange).focus()
									        $(textRange).select();
									        document.execCommand("Copy");
									   			 }


	$(document).ready(function() {
		
		
		$("#CRTYPE").click(function() {

			compteRenduType = "{{compteRenduType}}".replace(/xx/g,"\n")
			copyToClipboard(compteRenduType, id="#textarea");
  			   			 					
			alert(compteRenduType)	

		} );

				});
	</script>
{% endblock autre_script%}

gestion_patient/templates/radiographies_main.html
{% extends "radiographies_pulmonaire.html" %}
{% load static %}


{% block autre_script %}


	<script>


	function copyToClipboard(element, id) {
									        textRange = $(id);
									        
									        textRange.html(element)
									        //$(textRange).focus()
									        $(textRange).select();
									        document.execCommand("Copy");
									   			 }


	$(document).ready(function() {
		
		
		$("#CRTYPE").click(function() {

			compteRenduType = "{{compteRenduType}}".replace(/xx/g,"\n")
			copyToClipboard(compteRenduType, id="#textarea");
  			   			 					
			alert(compteRenduType)	

		} );

				});
	</script>
{% endblock autre_script%}

gestion_patient/templates/rentrer_patient.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Titre</title>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="static/materialize/css/materialize.css"/>

    	<script src="static/jquery-3.2.1.js"> </script>
    	<script type="text/javascript" src="static/materialize/js/materialize.min.js"></script>
    </head>

    <body class="grey lighten-2">

            

        <div class="titre blue"> <h3>DEMANDE EXAMEN RADIOLOGIQUE</h3> </div>
        <div class="section"></div>
        
        <div class="row">
          <div class="col s7">
            <div class="card white ">
            <div class="card-content black-text">
              
               <form action="rentrer_patient.html" method="post">
            {% csrf_token %}
            {{form.as_table}}
                    <div class="col s12">
                        <button class="btn waves-effect waves-light blue lighten-2" id="bouton_submit">Submit

                            <i class="material-icons right">send</i>
                        </button>
                    </div>
               </form>
            </div>
          </div>
        </div>
      </div>
        
       
        <div class="section"></div>
        <div class="col s12">
            <button class="btn waves-effect waves-light blue" id="bouton_afficher">afficher la liste des patients en attente
                <i class="material-icons right">send</i>
            </button>
            
        </div>
<script>
$(document).ready(function() {
    $('select').material_select();
    $('#id_indication').css("height","100px");
    $('#bouton_afficher').click(function(){
            document.location.href="afficher_patient.html"; 
                });
  });
</script>

    	<script>
          
           
            
            
            
    	</script>

 
    </body>
</html>

gestion_patient/templates/scanner.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Titre</title>

        <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

        
    </head>

    <body class="white lighten-2">

        <nav>
            <div class="nav-wrapper blue lighten-2">
              <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="/radio/scanner/">Scanner</a></li>
                <li><a href="/radio/radiographies/">Radiographies</a></li>
                <li><a href="/radio/irm/">IRM</a></li>
                <li><a href="/radio/accueil/">Acceuil</a></li>
                <li><a class="btn waves-effect blue tooltipped " data-tooltip="réinitialiser" onclick="location.reload(true)"><i class="material-icons">autorenew</i></a></li>
                <li><a class="btn waves-effect blue tooltipped " data-tooltip="lancer le guide interactif" onclick="$('.premiere').dialog({height:400, width:800})";><i class="material-icons">child_friendly</i></a></li>
            </ul>
            <h3 class="title center">{% block titre %} SCANNER {% endblock titre %}</h3>

        </nav> 

        <div class="section"></div> 
    
      
     <!-- guide interactif -->  
    {% if guide %} 
    {% include "html/guide.html" with guide=guide %}
    {% endif %}


    {% block regions_anatomiques %}
        {% for item in liste %}
            {% include "html/collapsible_double.html" with a=item.region_anatomique liste=item.sous_rubriques titre=titre adresseImage=item.adresseImage path="Users/nicolas/Desktop/urgences/gestion_patient/static"%} 
        {% endfor %}
    {% endblock regions_anatomiques %}



{% block script %}        
<script>
$(document).ready(function() {
    M.AutoInit();
    $('.optionnel').hide()
    $('select').formSelect();
    $('.tooltipped').tooltip();
    $('#id_indication').css("height","100px");
    $('#bouton_afficher').click(function(){
            document.location.href="afficher_patient.html"; 
                });
  });
</script>
{% endblock script %} 


{% block formulaire %}
{% endblock formulaire %}

{% block contenu %}
{% endblock contenu %}

{% block autre_script %}
{% endblock autre_script %}

{% block CRspecifique %}
{% endblock CRspecifique %}